/**
 * Default recipient resolution when EmailGroup is missing, inactive, or empty.
 * roleNames match seed/roles.js. useRequester adds the document requester email from context.
 */
export const WORKFLOW_EMAIL_EVENT_KEYS = [
  'pr.created',
  'pr.whs.approved',
  'pr.pm.approved',
  'pr.rejected',
  'pr.sap.created',
  'pr.sap.failed',
  'po.created',
  'po.pm.approved',
  'po.finance.approved',
  'po.rejected',
  'po.sap.created',
  'po.sap.failed',
  'apri.warehouse.approved',
  'apri.warehouse.rejected',
  'apri.sap.created',
  'apri.sap.failed',
  'local_purchase.pending_pm',
  'local_purchase.pending_finance',
  'local_purchase.pm_approved',
  'local_purchase.rejected',
  'local_purchase.completed',
  'local_purchase.resubmitted',
  'local_purchase.cancelled',
];

export const EVENT_FALLBACK_RECIPIENTS = {
  'pr.created': { roleNames: ['WHS Approver'] },
  'pr.whs.approved': { roleNames: ['Project Manager'] },
  'pr.pm.approved': { roleNames: ['Requester'], useRequester: true },
  'pr.rejected': { roleNames: ['Requester'], useRequester: true },
  'pr.sap.created': { roleNames: ['Requester', 'Admin'], useRequester: true },
  'pr.sap.failed': { roleNames: ['Admin'] },
  'po.created': { roleNames: ['Project Manager'] },
  'po.pm.approved': { roleNames: ['Finance'] },
  'po.finance.approved': { roleNames: ['Requester', 'Procurement'], useRequester: true },
  'po.rejected': { roleNames: ['Requester'], useRequester: true },
  'po.sap.created': { roleNames: ['Requester', 'Procurement', 'Admin'], useRequester: true },
  'po.sap.failed': { roleNames: ['Admin'] },
  'apri.warehouse.approved': { roleNames: ['Procurement'], useRequester: true },
  'apri.warehouse.rejected': { roleNames: ['Procurement'], useRequester: true },
  'apri.sap.created': { roleNames: ['Finance', 'Procurement'], useRequester: true },
  'apri.sap.failed': { roleNames: ['Admin', 'Procurement'], useRequester: true },
  'local_purchase.pending_pm': { roleNames: ['Project Manager'] },
  'local_purchase.pending_finance': { roleNames: ['Finance'] },
  'local_purchase.pm_approved': { roleNames: ['Procurement'], useRequester: true },
  'local_purchase.rejected': { roleNames: ['Procurement'], useRequester: true },
  'local_purchase.completed': { roleNames: ['Procurement'], useRequester: true },
  'local_purchase.resubmitted': { roleNames: ['Project Manager'] },
  'local_purchase.cancelled': { roleNames: ['Procurement'], useRequester: true },
};

export const EVENT_LABELS = {
  'pr.created': 'PR submitted for approval',
  'pr.whs.approved': 'PR approved by warehouse — pending PM',
  'pr.pm.approved': 'PR fully approved',
  'pr.rejected': 'PR rejected',
  'pr.sap.created': 'PR created in SAP',
  'pr.sap.failed': 'PR SAP creation failed',
  'po.created': 'PO created — pending PM approval',
  'po.pm.approved': 'PO approved by PM — pending Finance',
  'po.finance.approved': 'PO fully approved',
  'po.rejected': 'PO rejected',
  'po.sap.created': 'PO created in SAP',
  'po.sap.failed': 'PO SAP creation failed',
  'apri.warehouse.approved': 'APRI approved by warehouse — ready for SAP',
  'apri.warehouse.rejected': 'APRI rejected by warehouse',
  'apri.sap.created': 'APRI created in SAP',
  'apri.sap.failed': 'APRI SAP creation failed',
  'local_purchase.pending_pm': 'Local Purchase pending PM approval',
  'local_purchase.pending_finance': 'Local Purchase pending Finance approval',
  'local_purchase.pm_approved': 'Local Purchase approved by PM — pending Finance',
  'local_purchase.rejected': 'Local Purchase rejected',
  'local_purchase.completed': 'Local Purchase completed',
  'local_purchase.resubmitted': 'Local Purchase resubmitted',
  'local_purchase.cancelled': 'Local Purchase cancelled',
};
